[package]
name = "interfaces"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
description = "Shared interfaces and traits for Ethos reputation system contracts"

[dependencies]
stylus-sdk = { workspace = true }
alloy-primitives = { workspace = true }

[lib]
crate-type = ["lib", "cdylib"]
